# Generated by Django 4.2 on 2023-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="qty", field=models.IntegerField(default=0),
        ),
    ]
